language: go
go:
  - 1.4
sudo: required
install:
  - sudo pip install Pygments
  - go get github.com/spf13/hugo
script: hugo
deploy:
	provider: script
	script: _bin/deploy.sh

env:
	global:
	  - GH_REF: github.com/nottinghamtec/Main-Website.git
	  - secure: "pm4b2VSVvIvxMU3cw7Yq1mLcvsEFselP0tMt+kcviFwZb1cYW7GZiG0vL1KXqpnD6bpHr8Q0jA4fzwX6e2+0Ft0DjEzDcptmSM2V9yMnJi1nA/losHUSAJ7mBoMO8mIW0ua3Hgtoso/AxLJz07hYGQUQK3qPnwvfuj0NVG3G2dp5J7cchDZssp1WAarkGY1UXbfzuX8NATDcZep72lX5dN9m+Lw1tmQrYPUgdNcuWTlJvUnJTt4kv27ow9h+/y7PG/en+2z5WFroi2xRSmAuWAndgJr52xcnoUMKUHb2uYKwV3OND4D18oawlloaOyZ7dKWec7/oZs/sdyzblkGoYan3XtZ4bnKYYNKAqvMSr8wMkt4IJDT3pIU0Kn+uY81N29Yo4ArH+p6KAOETOkaL3hvYsO2BFb6ecCE96c1b7zWJVEJanI/ICM1cI6sbt9uUIl/NoZxrSC3XOI2+oWMMFSKjtiaEMx9J95UsVHMqNzn/W4VwPdoxVpccZefGw8At0dMzu8638rf6lcazDGrWMQ+akySrSA+Jpdb5YZP6deTunTzETxoxtAGwGGyulR8WDi5xAD5Tlrt7/a67nOaHbMl9I2fkIgHwYsUDfUad6BOcxra+xF6StCt9FnNkei2PFJ5GriPMw/Psi1dbAkK3DaHfErTYPnj1fB6o+QtM9c0="