baseurl = "http://preview.nottinghamtec.co.uk/"
languageCode = "en-gb"
title = "TEC PA & Lighting"
PluralizeListTitles=false
canonifyurls = false

[[menu.main]]
	name = "Committee"
	identifier = "committee"
	parent = "About"
	url = "/committee/"
