baseurl = "http://www.nottinghamtec.co.uk/"
languageCode = "en-gb"
title = "TEC PA & Lighting"
PluralizeListTitles=false
canonifyurls = false

[[menu.main]]
    name = "Venues"
    weight = 2
    parent = "About"
    identifier = "venues"
    url = "/venues/"
