baseurl = "http://www.nottinghamtec.co.uk/"
languageCode = "en-gb"
title = "TEC PA & Lighting"
PluralizeListTitles=false
canonifyurls = false


[taxonomies]
photo = "photos"
title = "titles"
placement = "placements"

[[menu.main]]
    name = "Venues"
    weight = 1
    parent = "About"
    identifier = "venues"
    url = "/venues/"
